# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from service_spec import adr_pb2 as service__spec_dot_adr__pb2


class ServiceDefinitionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DownloadFile = channel.unary_stream(
        '/adr.ServiceDefinition/DownloadFile',
        request_serializer=service__spec_dot_adr__pb2.MetaData.SerializeToString,
        response_deserializer=service__spec_dot_adr__pb2.FileResponse.FromString,
        )
    self.ADR = channel.stream_unary(
        '/adr.ServiceDefinition/ADR',
        request_serializer=service__spec_dot_adr__pb2.UploadFileRequest.SerializeToString,
        response_deserializer=service__spec_dot_adr__pb2.StringResponse.FromString,
        )


class ServiceDefinitionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DownloadFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ADR(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServiceDefinitionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DownloadFile': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadFile,
          request_deserializer=service__spec_dot_adr__pb2.MetaData.FromString,
          response_serializer=service__spec_dot_adr__pb2.FileResponse.SerializeToString,
      ),
      'ADR': grpc.stream_unary_rpc_method_handler(
          servicer.ADR,
          request_deserializer=service__spec_dot_adr__pb2.UploadFileRequest.FromString,
          response_serializer=service__spec_dot_adr__pb2.StringResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'adr.ServiceDefinition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
